### PR TITLE
Update material version and fixed name of code

### LINKED ISSUE #34: Exception with some resources inside the file
Hi @KrishnaMoorthy12,

Thanks for using my library :) your project is very cool.

I'm training to run the project in my ide and I have a reception during the following use case:

Setting -> Conf. -> Save

<details>
<summary>This is the  exception</summary>
<br>
Exception
<br><br>
<pre>

```
/usr/lib/jvm/jdk-13.0.2/bin/java -javaagent:/home/vincent/.program/idea-IU-193.5662.53/lib/idea_rt.jar=44607:/home/vincent/.program/idea-IU-193.5662.53/bin -Dfile.encoding=UTF-8 -classpath /home/vincent/Github/trident/target/classes:/home/vincent/.m2/repository/io/github/vincenzopalazzo/material-ui-swing/1.1.1_pre-release_6.1/material-ui-swing-1.1.1_pre-release_6.1.jar:/home/vincent/.m2/repository/org/swinglabs/swingx/1.6.1/swingx-1.6.1.jar:/home/vincent/.m2/repository/com/jhlabs/filters/2.0.235/filters-2.0.235.jar:/home/vincent/.m2/repository/org/swinglabs/swing-worker/1.1/swing-worker-1.1.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-bundle/1.4.0/jiconfont-bundle-1.4.0.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-font_awesome/4.7.0.1/jiconfont-font_awesome-4.7.0.1.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-open_iconic/1.1.1.3/jiconfont-open_iconic-1.1.1.3.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-elusive/2.0.3/jiconfont-elusive-2.0.3.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-entypo/2.0.3/jiconfont-entypo-2.0.3.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-typicons/2.0.7.1/jiconfont-typicons-2.0.7.1.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-swing/1.0.1/jiconfont-swing-1.0.1.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont/1.0.0/jiconfont-1.0.0.jar:/home/vincent/.m2/repository/com/github/jiconfont/jiconfont-google_material_design_icons/2.2.0.2/jiconfont-google_material_design_icons-2.2.0.2.jar Trident
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/FoldingData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.FoldingData
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/FoldingData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.FoldingData
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/ReferenceData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.ReferenceData
Exception "java.lang.ClassNotFoundException: com/intellij/codeInsight/editorActions/ReferenceData"while constructing DataFlavor for: application/x-java-jvm-local-objectref; class=com.intellij.codeInsight.editorActions.ReferenceData
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at Configurations.write(Configurations.java:426)
	at ConfigurationsListener.actionPerformed(Configurations.java:526)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
java.io.IOException: No such file or directory
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(File.java:1024)
	at Trident.writeLog(Trident.java:149)
	at Trident.ErrorDialog(Trident.java:118)
	at FileMenuListener.actionPerformed(FileMenuListener.java:373)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6636)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
</pre>
</details>

Also, I want to ask, you are some ideas to introduce the syntax highlights?

I'm Dyslexic and this font [OpenDyslexia](https://opendyslexic.org/) helps me.

You load the font only from the system or you can load the font also to the repository?

### PR DESCRIPTION
**Pull request by vincenzopalazzo**
I try to compile this code with my IDE (IntelliJ) and don't work, I renamed the name of the file in ts to tcf and now walks.

I have a very small question, why you using the text file and don't and xml or a propriety file?

Have a good weekend

### CODE REVIEW

**Comment by krissh-codes** [comment]
Hi there, thanks for your help. I really appreciate it. I had already changed the file extension yesterday (in my country) ~ 16 hours ago. I wonder why you didn't get the recent changes.. Did I forget to push my commits...? Will check it out.

I've gone with plain text for the configurations, so that it'll be readable by users with absolutely no programming knowledge. In case someone messes up with configurations.. (The options in configurations aren't highly stable and reliable yet) and can't open the editor anymore, they can easily change the values in the file themselves.

I'm glad that tried my project. I'm looking forward to make a new release this weekend. I'll be fixing many bugs with configurations. Can I ask you some help when needed?
Thanks again.

**Comment by vincenzopalazzo** [comment]
Hi @KrishnaMoorthy12,

I noted that you have lost something, a file with extension .ts is very strange :)

I like your project because is very cool with swing, It is a game :) and I like the games.

But I want to add also more details:

>I've gone with plain text for the configurations, so that it'll be readable by users with absolutely no programming knowledge. In case someone messes up with configurations.. (The options in configurations aren't highly stable and reliable yet) and can't open the editor anymore, they can easily change the values in the file themselves.

I think the existing solution better, like file proprieties, you image this configuration:

```
THEME=MATERIAL_DARK
SPACE=4
```

It is more configurable than the file proprieties.

>Can I ask you some help when needed?

Absolutely, you can create a slack workspace, if you want.

> (The options in configurations aren't highly stable and reliable yet)

I see I think the Configuration class can be improved

**Comment by krissh-codes** [comment]
>
> I noted that you have lost something, a file with extension .ts is very strange :)
>
Yes, you're 100% right. And that's why I changed it to tcf (Abbr. Trident Configuration File)

> I like your project because is very cool with swing, It is a game :) and I like the games.

Game??? 😳 You mean you like to swing? 😹😹 I like it too.

>
> I think the existing solution better, like file proprieties, you image this configuration:
> 
> ```
> THEME=MATERIAL_DARK
> SPACE=4
> ```

You're right. I'll try to make it possible. But it'll involve some more work.

**Comment by vincenzopalazzo** [comment]
@KrishnaMoorthy12 

>Game??? flushed You mean you like to swing? joy_catjoy_cat I like it too.

Yes create an editor text with sublime with a very cool game, right? :)

>You're right. I'll try to make it possible. But it'll involve some more work.

I can help you to refactoring the class if you want

**Comment by krissh-codes** [comment]
That'll be great. I have just created a slack account. I'm learning to use it.. will try to join there asap.

**Comment by vincenzopalazzo** [comment]
@KrishnaMoorthy12 can add me with the my dev mail vincenzopalazzodev@gmail.com

**Review by krissh-codes — APPROVED** [review]

**Comment by krissh-codes** [comment]
### Dependency update:
material-swing

**Comment by krissh-codes** [comment]
>  I think the existing solution better, like file proprieties, you image this configuration:
>  ```
>  THEME=MATERIAL_DARK
>  SPACE=4
>  ```
> 
Partially implemented: f7467647bfa490b4e2fa102c6c181c500e79077e and tested.

**Pull request merged**
